<a href="https://colab.research.google.com/github/Sayaliravindrapatil/Bike-rental--OOPS-based/blob/main/Sentimental_Analysis_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
pip install nltk


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
df_=pd.read_csv("/content/dataset[1].csv",nrows=2000)



In [ ]:
df_.head()

,Text,Language,Label
0,@Charlie_Corley @Kristine1G @amyklobuchar @Sty...,en,litigious
1,#BadBunny: Como dos gotas de agua: Joven se di...,es,negative
2,https://t.co/YJNiO0p1JV Flagstar Bank disclose...,en,litigious
3,Rwanda is set to host the headquarters of Unit...,en,positive
4,OOPS. I typed her name incorrectly (today’s br...,en,litigious


In [ ]:
features=df_["Text"]
labels=df_["Label"]
df_.head()

,Text,Language,Label
0,@Charlie_Corley @Kristine1G @amyklobuchar @Sty...,en,litigious
1,#BadBunny: Como dos gotas de agua: Joven se di...,es,negative
2,https://t.co/YJNiO0p1JV Flagstar Bank disclose...,en,litigious
3,Rwanda is set to host the headquarters of Unit...,en,positive
4,OOPS. I typed her name incorrectly (today’s br...,en,litigious


# **Conerting tweets to string datatype**

In [ ]:
df_["Text"]=df_["Text"].astype(str)

# **Converting to lower case features**

In [ ]:
features=(features.str.lower())
features

0       @charlie_corley @kristine1g @amyklobuchar @sty...
1       #badbunny: como dos gotas de agua: joven se di...
2       https://t.co/yjnio0p1jv flagstar bank disclose...
3       rwanda is set to host the headquarters of unit...
4       oops. i typed her name incorrectly (today’s br...
                              ...                        
1995    @jonikauf’s outfit goes crazy in lost kingdom ...
1996    this.\n\nlaws are not ethics. if a law is unet...
1997    @transportgovuk university of the west of engl...
1998    @usspacelawyer @garym03062 @commentary a witne...
1999    @matheuspereira everyone knows that you are a ...
Name: Text, Length: 2000, dtype: object

# **Removing punctuation marks**

---



In [ ]:
import string

punctuations=set(string.punctuation)
k=list(punctuations)
# print(k)
emp=[]
for i in features:
  emp1=""
  for j in i:
    if j not  in k:
      emp1+=j
  emp.append(emp1)

print(emp)
len(emp)
pd.set_option("display.max_colwidth",-1)



['charliecorley kristine1g amyklobuchar stylewriternyc testimony is not evidence in a court of law state or federal must stand up to cross examination', 'badbunny como dos gotas de agua joven se disfraza de bad bunny y causa tumulto en alfombra roja httpstco3524seangh', 'httpstcoyjnio0p1jv flagstar bank discloses a data breach that impacted 15\nmillion individuals cybersecurity', 'rwanda is set to host the headquarters of united nations development programme’s undp new innovation financing facility \n\nfind out more httpstcobznktc8pl0\n\nsovereigngroup sovereignafrica undp rwanda', 'oops i typed her name incorrectly today’s brave witness cassidyhutchinson 6 premeditatedviolence 7 probaby witnesstamperig don’t forget markmeadows requesting a pardon trumpknew trumpcapitolcoupattack capitolcoupattempt neverforgetjanuary6th neverforgetjan6th httpstcooexm3hdwnz', 'it sucks for me since im focused on the nature aspect of things but the environmental problems we have all have their roots in s

<ipython-input-8-6284b5e8f0b3>:16: FutureWarning: Passing a negative integer is deprecated in version 1.0 and will not be supported in future version. Instead, use None to not limit the column width.
  pd.set_option("display.max_colwidth",-1)


In [ ]:
df_["Tweets_w/o_punctuations"]=emp

In [ ]:
df_

,Text,Language,Label,Tweets_w/o_punctuations
0,"@Charlie_Corley @Kristine1G @amyklobuchar @StyleWriterNYC testimony is NOT evidence in a court of law, state or federal. Must stand up to cross examination",en,litigious,charliecorley kristine1g amyklobuchar stylewriternyc testimony is not evidence in a court of law state or federal must stand up to cross examination
1,#BadBunny: Como dos gotas de agua: Joven se disfraza de Bad Bunny y causa tumulto en alfombra roja. https://t.co/3524SEangh,es,negative,badbunny como dos gotas de agua joven se disfraza de bad bunny y causa tumulto en alfombra roja httpstco3524seangh
2,https://t.co/YJNiO0p1JV Flagstar Bank discloses a data breach that impacted 1.5\nMillion individuals #cybersecurity,en,litigious,httpstcoyjnio0p1jv flagstar bank discloses a data breach that impacted 15\nmillion individuals cybersecurity
3,Rwanda is set to host the headquarters of United Nations Development Programme’s (UNDP) new innovation financing facility. \n\nFind out more: https://t.co/BznkTC8pl0\n\n#SovereignGroup #SovereignAfrica #UNDP #Rwanda,en,positive,rwanda is set to host the headquarters of united nations development programme’s undp new innovation financing facility \n\nfind out more httpstcobznktc8pl0\n\nsovereigngroup sovereignafrica undp rwanda
4,OOPS. I typed her name incorrectly (today’s brave witness) #CassidyHutchinson. 6. #PremeditatedViolence 7. (probaby) #WitnessTamperig. Don’t forget #MarkMeadows requesting a #Pardon. #TrumpKnew #TrumpCapitolCoupAttack #CapitolCoupAttempt #NeverForgetJanuary6th #NeverForgetJan6th https://t.co/oeXM3hDWnZ,en,litigious,oops i typed her name incorrectly today’s brave witness cassidyhutchinson 6 premeditatedviolence 7 probaby witnesstamperig don’t forget markmeadows requesting a pardon trumpknew trumpcapitolcoupattack capitolcoupattempt neverforgetjanuary6th neverforgetjan6th httpstcooexm3hdwnz
...,...,...,...,...
1995,@JoniKauf’s outfit goes crazy in Lost Kingdom https://t.co/rn9IdIOJwC,en,negative,jonikauf’s outfit goes crazy in lost kingdom httpstcorn9idiojwc
1996,"THIS.\n\nLaws are NOT ethics. If a law is unethical you can make the choice to act ethically, even if it is a huge risk to you and/or your career. You can choose to protect people, and do the right thing.\n\nYeah, it's scary, but sometimes the right thing is scary. https://t.co/QJ69IDpjBI",en,litigious,this\n\nlaws are not ethics if a law is unethical you can make the choice to act ethically even if it is a huge risk to you andor your career you can choose to protect people and do the right thing\n\nyeah its scary but sometimes the right thing is scary httpstcoqj69idpjbi
1997,"@transportgovuk university of the West of England frenchay Bristol , the one way system is in breach of the highway code, buses often try to drive into me expecting me to give way to them when they're on my left, something needs to be done so buses are on the right https://t.co/qQc1PPcNx6",en,litigious,transportgovuk university of the west of england frenchay bristol the one way system is in breach of the highway code buses often try to drive into me expecting me to give way to them when theyre on my left something needs to be done so buses are on the right httpstcoqqc1ppcnx6
1998,"@USSpaceLawyer @GaryM03062 @Commentary A witness repeating what a non-testifying declarant told her for the purpose of proving the truth of the declarant's statement (i.e., things Trump allegedly did) is most definitely hearsay.",en,litigious,usspacelawyer garym03062 commentary a witness repeating what a nontestifying declarant told her for the purpose of proving the truth of the declarants statement ie things trump allegedly did is most definitely hearsay


# **Removing stopwords**

In [ ]:
import nltk
nltk.download()

# DWONLOAD-->stopwords-->QUIT

NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> 

---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> 

---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> d

Download which package (l=list; x=cancel)?
  Identifier> stopwords


      Unzipping corpora/stopwords.zip.



---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> q


True

In [ ]:
import nltk
from nltk.corpus import stopwords
df_li=[]
sent_li=[]
for sent in df_["Tweets_w/o_punctuations"]:
  words_li=[]
  for word in sent.split():
    if word not in stopwords.words('english'):
      words_li.append(word)
  sent_li.append(" ".join(words_li))


In [ ]:
df_['Tweets_w/o_stopwords']=pd.Series(sent_li,index=df_.index)

In [ ]:
df_.head()

,Text,Language,Label,Tweets_w/o_punctuations,Tweets_w/o_stopwords
0,"@Charlie_Corley @Kristine1G @amyklobuchar @StyleWriterNYC testimony is NOT evidence in a court of law, state or federal. Must stand up to cross examination",en,litigious,charliecorley kristine1g amyklobuchar stylewriternyc testimony is not evidence in a court of law state or federal must stand up to cross examination,charliecorley kristine1g amyklobuchar stylewriternyc testimony evidence court law state federal must stand cross examination
1,#BadBunny: Como dos gotas de agua: Joven se disfraza de Bad Bunny y causa tumulto en alfombra roja. https://t.co/3524SEangh,es,negative,badbunny como dos gotas de agua joven se disfraza de bad bunny y causa tumulto en alfombra roja httpstco3524seangh,badbunny como dos gotas de agua joven se disfraza de bad bunny causa tumulto en alfombra roja httpstco3524seangh
2,https://t.co/YJNiO0p1JV Flagstar Bank discloses a data breach that impacted 1.5\nMillion individuals #cybersecurity,en,litigious,httpstcoyjnio0p1jv flagstar bank discloses a data breach that impacted 15\nmillion individuals cybersecurity,httpstcoyjnio0p1jv flagstar bank discloses data breach impacted 15 million individuals cybersecurity
3,Rwanda is set to host the headquarters of United Nations Development Programme’s (UNDP) new innovation financing facility. \n\nFind out more: https://t.co/BznkTC8pl0\n\n#SovereignGroup #SovereignAfrica #UNDP #Rwanda,en,positive,rwanda is set to host the headquarters of united nations development programme’s undp new innovation financing facility \n\nfind out more httpstcobznktc8pl0\n\nsovereigngroup sovereignafrica undp rwanda,rwanda set host headquarters united nations development programme’s undp new innovation financing facility find httpstcobznktc8pl0 sovereigngroup sovereignafrica undp rwanda
4,OOPS. I typed her name incorrectly (today’s brave witness) #CassidyHutchinson. 6. #PremeditatedViolence 7. (probaby) #WitnessTamperig. Don’t forget #MarkMeadows requesting a #Pardon. #TrumpKnew #TrumpCapitolCoupAttack #CapitolCoupAttempt #NeverForgetJanuary6th #NeverForgetJan6th https://t.co/oeXM3hDWnZ,en,litigious,oops i typed her name incorrectly today’s brave witness cassidyhutchinson 6 premeditatedviolence 7 probaby witnesstamperig don’t forget markmeadows requesting a pardon trumpknew trumpcapitolcoupattack capitolcoupattempt neverforgetjanuary6th neverforgetjan6th httpstcooexm3hdwnz,oops typed name incorrectly today’s brave witness cassidyhutchinson 6 premeditatedviolence 7 probaby witnesstamperig don’t forget markmeadows requesting pardon trumpknew trumpcapitolcoupattack capitolcoupattempt neverforgetjanuary6th neverforgetjan6th httpstcooexm3hdwnz


# **Removing all the links**

import re


emp_list=[]


for i in df_["Tweets_w/o_stopwords"]:


  new_text=re.sub(r"\b" + "https" + r"\w+", "", i)


  emp_list.append(new_text)


df_["Tweets_w/o_links"]=emp_list


df_.head()

---

In this way also the code can be written

In [ ]:
import re
df_["Tweets_w/o_links"]=df_["Tweets_w/o_stopwords"].map(lambda i:re.sub(r"\b" + "https" + r"\w+", "", i))
df_.head()

,Text,Language,Label,Tweets_w/o_punctuations,Tweets_w/o_stopwords,Tweets_w/o_links
0,"@Charlie_Corley @Kristine1G @amyklobuchar @StyleWriterNYC testimony is NOT evidence in a court of law, state or federal. Must stand up to cross examination",en,litigious,charliecorley kristine1g amyklobuchar stylewriternyc testimony is not evidence in a court of law state or federal must stand up to cross examination,charliecorley kristine1g amyklobuchar stylewriternyc testimony evidence court law state federal must stand cross examination,charliecorley kristine1g amyklobuchar stylewriternyc testimony evidence court law state federal must stand cross examination
1,#BadBunny: Como dos gotas de agua: Joven se disfraza de Bad Bunny y causa tumulto en alfombra roja. https://t.co/3524SEangh,es,negative,badbunny como dos gotas de agua joven se disfraza de bad bunny y causa tumulto en alfombra roja httpstco3524seangh,badbunny como dos gotas de agua joven se disfraza de bad bunny causa tumulto en alfombra roja httpstco3524seangh,badbunny como dos gotas de agua joven se disfraza de bad bunny causa tumulto en alfombra roja
2,https://t.co/YJNiO0p1JV Flagstar Bank discloses a data breach that impacted 1.5\nMillion individuals #cybersecurity,en,litigious,httpstcoyjnio0p1jv flagstar bank discloses a data breach that impacted 15\nmillion individuals cybersecurity,httpstcoyjnio0p1jv flagstar bank discloses data breach impacted 15 million individuals cybersecurity,flagstar bank discloses data breach impacted 15 million individuals cybersecurity
3,Rwanda is set to host the headquarters of United Nations Development Programme’s (UNDP) new innovation financing facility. \n\nFind out more: https://t.co/BznkTC8pl0\n\n#SovereignGroup #SovereignAfrica #UNDP #Rwanda,en,positive,rwanda is set to host the headquarters of united nations development programme’s undp new innovation financing facility \n\nfind out more httpstcobznktc8pl0\n\nsovereigngroup sovereignafrica undp rwanda,rwanda set host headquarters united nations development programme’s undp new innovation financing facility find httpstcobznktc8pl0 sovereigngroup sovereignafrica undp rwanda,rwanda set host headquarters united nations development programme’s undp new innovation financing facility find sovereigngroup sovereignafrica undp rwanda
4,OOPS. I typed her name incorrectly (today’s brave witness) #CassidyHutchinson. 6. #PremeditatedViolence 7. (probaby) #WitnessTamperig. Don’t forget #MarkMeadows requesting a #Pardon. #TrumpKnew #TrumpCapitolCoupAttack #CapitolCoupAttempt #NeverForgetJanuary6th #NeverForgetJan6th https://t.co/oeXM3hDWnZ,en,litigious,oops i typed her name incorrectly today’s brave witness cassidyhutchinson 6 premeditatedviolence 7 probaby witnesstamperig don’t forget markmeadows requesting a pardon trumpknew trumpcapitolcoupattack capitolcoupattempt neverforgetjanuary6th neverforgetjan6th httpstcooexm3hdwnz,oops typed name incorrectly today’s brave witness cassidyhutchinson 6 premeditatedviolence 7 probaby witnesstamperig don’t forget markmeadows requesting pardon trumpknew trumpcapitolcoupattack capitolcoupattempt neverforgetjanuary6th neverforgetjan6th httpstcooexm3hdwnz,oops typed name incorrectly today’s brave witness cassidyhutchinson 6 premeditatedviolence 7 probaby witnesstamperig don’t forget markmeadows requesting pardon trumpknew trumpcapitolcoupattack capitolcoupattempt neverforgetjanuary6th neverforgetjan6th


# **Tokenization**

In [ ]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [ ]:
token=[i.split() for i in df_["Tweets_w/o_links"]]
df_["token"]=token
df_.head()

,Text,Language,Label,Tweets_w/o_punctuations,Tweets_w/o_stopwords,Tweets_w/o_links,token
0,"@Charlie_Corley @Kristine1G @amyklobuchar @StyleWriterNYC testimony is NOT evidence in a court of law, state or federal. Must stand up to cross examination",en,litigious,charliecorley kristine1g amyklobuchar stylewriternyc testimony is not evidence in a court of law state or federal must stand up to cross examination,charliecorley kristine1g amyklobuchar stylewriternyc testimony evidence court law state federal must stand cross examination,charliecorley kristine1g amyklobuchar stylewriternyc testimony evidence court law state federal must stand cross examination,"[charliecorley, kristine1g, amyklobuchar, stylewriternyc, testimony, evidence, court, law, state, federal, must, stand, cross, examination]"
1,#BadBunny: Como dos gotas de agua: Joven se disfraza de Bad Bunny y causa tumulto en alfombra roja. https://t.co/3524SEangh,es,negative,badbunny como dos gotas de agua joven se disfraza de bad bunny y causa tumulto en alfombra roja httpstco3524seangh,badbunny como dos gotas de agua joven se disfraza de bad bunny causa tumulto en alfombra roja httpstco3524seangh,badbunny como dos gotas de agua joven se disfraza de bad bunny causa tumulto en alfombra roja,"[badbunny, como, dos, gotas, de, agua, joven, se, disfraza, de, bad, bunny, causa, tumulto, en, alfombra, roja]"
2,https://t.co/YJNiO0p1JV Flagstar Bank discloses a data breach that impacted 1.5\nMillion individuals #cybersecurity,en,litigious,httpstcoyjnio0p1jv flagstar bank discloses a data breach that impacted 15\nmillion individuals cybersecurity,httpstcoyjnio0p1jv flagstar bank discloses data breach impacted 15 million individuals cybersecurity,flagstar bank discloses data breach impacted 15 million individuals cybersecurity,"[flagstar, bank, discloses, data, breach, impacted, 15, million, individuals, cybersecurity]"
3,Rwanda is set to host the headquarters of United Nations Development Programme’s (UNDP) new innovation financing facility. \n\nFind out more: https://t.co/BznkTC8pl0\n\n#SovereignGroup #SovereignAfrica #UNDP #Rwanda,en,positive,rwanda is set to host the headquarters of united nations development programme’s undp new innovation financing facility \n\nfind out more httpstcobznktc8pl0\n\nsovereigngroup sovereignafrica undp rwanda,rwanda set host headquarters united nations development programme’s undp new innovation financing facility find httpstcobznktc8pl0 sovereigngroup sovereignafrica undp rwanda,rwanda set host headquarters united nations development programme’s undp new innovation financing facility find sovereigngroup sovereignafrica undp rwanda,"[rwanda, set, host, headquarters, united, nations, development, programme’s, undp, new, innovation, financing, facility, find, sovereigngroup, sovereignafrica, undp, rwanda]"
4,OOPS. I typed her name incorrectly (today’s brave witness) #CassidyHutchinson. 6. #PremeditatedViolence 7. (probaby) #WitnessTamperig. Don’t forget #MarkMeadows requesting a #Pardon. #TrumpKnew #TrumpCapitolCoupAttack #CapitolCoupAttempt #NeverForgetJanuary6th #NeverForgetJan6th https://t.co/oeXM3hDWnZ,en,litigious,oops i typed her name incorrectly today’s brave witness cassidyhutchinson 6 premeditatedviolence 7 probaby witnesstamperig don’t forget markmeadows requesting a pardon trumpknew trumpcapitolcoupattack capitolcoupattempt neverforgetjanuary6th neverforgetjan6th httpstcooexm3hdwnz,oops typed name incorrectly today’s brave witness cassidyhutchinson 6 premeditatedviolence 7 probaby witnesstamperig don’t forget markmeadows requesting pardon trumpknew trumpcapitolcoupattack capitolcoupattempt neverforgetjanuary6th neverforgetjan6th httpstcooexm3hdwnz,oops typed name incorrectly today’s brave witness cassidyhutchinson 6 premeditatedviolence 7 probaby witnesstamperig don’t forget markmeadows requesting pardon trumpknew trumpcapitolcoupattack capitolcoupattempt neverforgetjanuary6th neverforgetjan6th,"[oops, typed, name, incorrectly, today’s, bra

# **Lemmatization**

In [ ]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.


True

In [ ]:
import nltk
nltk.download()

#Download-->wordnet-->quit

NLTK Downloader
---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> d

Download which package (l=list; x=cancel)?
  Identifier> wordnet



---------------------------------------------------------------------------
    d) Download   l) List    u) Update   c) Config   h) Help   q) Quit
---------------------------------------------------------------------------
Downloader> q


True

In [ ]:
list2=df_["token"].map(nltk.pos_tag)
list2

0       [(charliecorley, NN), (kristine1g, NN), (amyklobuchar, NN), (stylewriternyc, NN), (testimony, NN), (evidence, NN), (court, NN), (law, NN), (state, NN), (federal, JJ), (must, MD), (stand, VB), (cross, NN), (examination, NN)]                                                                                                                                                                                                   
1       [(badbunny, NN), (como, NN), (dos, JJ), (gotas, NN), (de, IN), (agua, FW), (joven, FW), (se, FW), (disfraza, FW), (de, FW), (bad, JJ), (bunny, NN), (causa, NN), (tumulto, NN), (en, IN), (alfombra, NN), (roja, NN)]                                                                                                                                                                                                             
2       [(flagstar, NN), (bank, NN), (discloses, VBZ), (data, NNS), (breach, NN), (impacted, VBD), (15, CD), (million, CD), (individuals, NNS), (c

In [ ]:
from nltk.text import TokenSearcher
from nltk.sem.logic import Tokens
from nltk.corpus import wordnet

def get_wordnet_pos(i):
  # for i in my_dict.values():
    if i.startswith('J'):
        return wordnet.ADJ
    elif i.startswith('V'):
        return wordnet.VERB
    elif i.startswith('N'):
        return wordnet.NOUN
    elif i.startswith('R'):
        return wordnet.ADV
    else:
        return ''



In [ ]:
lem=list(map(lambda x: {i:get_wordnet_pos(j) for i,j in x },list2))
lem

In [ ]:
from nltk.stem import WordNetLemmatizer
nltk.download('averaged_perceptron_tagger')
from nltk.corpus import wordnet


[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


In [ ]:
lemmatizer = WordNetLemmatizer()
list33=[]
for i in lem:
  list3=[]
  for k,v in i.items():
    if v=='':
      v='n'
    lemmatized_words=lemmatizer.lemmatize(k, pos=v)
    list3.append(lemmatized_words)
  list33.append(" ".join(list3))
# print(list33)

In [ ]:
df_["Lemmatized_sentences"]=list33
df_

# **Count Vectorization**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()

In [ ]:
df_.head()

,Text,Language,Label,Tweets_w/o_punctuations,Tweets_w/o_stopwords,Tweets_w/o_links,token,Lemmatized_sentences
0,"@Charlie_Corley @Kristine1G @amyklobuchar @StyleWriterNYC testimony is NOT evidence in a court of law, state or federal. Must stand up to cross examination",en,litigious,charliecorley kristine1g amyklobuchar stylewriternyc testimony is not evidence in a court of law state or federal must stand up to cross examination,charliecorley kristine1g amyklobuchar stylewriternyc testimony evidence court law state federal must stand cross examination,charliecorley kristine1g amyklobuchar stylewriternyc testimony evidence court law state federal must stand cross examination,"[charliecorley, kristine1g, amyklobuchar, stylewriternyc, testimony, evidence, court, law, state, federal, must, stand, cross, examination]",charliecorley kristine1g amyklobuchar stylewriternyc testimony evidence court law state federal must stand cross examination
1,#BadBunny: Como dos gotas de agua: Joven se disfraza de Bad Bunny y causa tumulto en alfombra roja. https://t.co/3524SEangh,es,negative,badbunny como dos gotas de agua joven se disfraza de bad bunny y causa tumulto en alfombra roja httpstco3524seangh,badbunny como dos gotas de agua joven se disfraza de bad bunny causa tumulto en alfombra roja httpstco3524seangh,badbunny como dos gotas de agua joven se disfraza de bad bunny causa tumulto en alfombra roja,"[badbunny, como, dos, gotas, de, agua, joven, se, disfraza, de, bad, bunny, causa, tumulto, en, alfombra, roja]",badbunny como dos gotas de agua joven se disfraza bad bunny causa tumulto en alfombra roja
2,https://t.co/YJNiO0p1JV Flagstar Bank discloses a data breach that impacted 1.5\nMillion individuals #cybersecurity,en,litigious,httpstcoyjnio0p1jv flagstar bank discloses a data breach that impacted 15\nmillion individuals cybersecurity,httpstcoyjnio0p1jv flagstar bank discloses data breach impacted 15 million individuals cybersecurity,flagstar bank discloses data breach impacted 15 million individuals cybersecurity,"[flagstar, bank, discloses, data, breach, impacted, 15, million, individuals, cybersecurity]",flagstar bank disclose data breach impact 15 million individual cybersecurity
3,Rwanda is set to host the headquarters of United Nations Development Programme’s (UNDP) new innovation financing facility. \n\nFind out more: https://t.co/BznkTC8pl0\n\n#SovereignGroup #SovereignAfrica #UNDP #Rwanda,en,positive,rwanda is set to host the headquarters of united nations development programme’s undp new innovation financing facility \n\nfind out more httpstcobznktc8pl0\n\nsovereigngroup sovereignafrica undp rwanda,rwanda set host headquarters united nations development programme’s undp new innovation financing facility find httpstcobznktc8pl0 sovereigngroup sovereignafrica undp rwanda,rwanda set host headquarters united nations development programme’s undp new innovation financing facility find sovereigngroup sovereignafrica undp rwanda,"[rwanda, set, host, headquarters, united, nations, development, programme’s, undp, new, innovation, financing, facility, find, sovereigngroup, sovereignafrica, undp, rwanda]",rwanda set host headquarters united nation development programme’s undp new innovation financing facility find sovereigngroup sovereignafrica
4,OOPS. I typed her name incorrectly (today’s brave witness) #CassidyHutchinson. 6. #PremeditatedViolence 7. (probaby) #WitnessTamperig. Don’t forget #MarkMeadows requesting a #Pardon. #TrumpKnew #TrumpCapitolCoupAttack #CapitolCoupAttempt #NeverForgetJanuary6th #NeverForgetJan6th https://t.co/oeXM3hDWnZ,en,litigious,oops i typed her name incorrectly today’s brave witness cassidyhutchinson 6 premeditatedviolence 7 probaby witnesstamperig don’t forget markmeadows requesting a pardon trumpknew trumpcapitolcoupattack capitolcoupattempt neverforgetjanuary6th neverforgetjan6th httpstcooexm3hdwnz,oops typed name incorrectly today’s brave witness cassidyhutchinson 6 premeditatedviolence 7 probaby witnesstamp

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df_["Lemmatized_sentences"], df_["Label"],random_state=0)

In [ ]:
vect_train = vectorizer.fit_transform(X_train).toarray()
vect_train

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:
vocab_dict = vectorizer.vocabulary_.copy()
dict(sorted(vocab_dict.items(), key=lambda item: item[1]))

In [ ]:
vect_test = vectorizer.transform(X_test).toarray()
vect_test

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [ ]:

from sklearn.svm import SVC

In [ ]:
labels.unique()

array(['litigious', 'negative', 'positive', 'uncertainty'], dtype=object)

In [ ]:
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
nb.fit(vect_train,y_train)
nb.score(vect_train, y_train),nb.score(vect_test, y_test)

(0.988, 0.44)

In [ ]:
vect_test, y_test

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]),
 405     litigious  
 1190    positive   
 1132    uncertainty
 731     negative   
 1754    uncertainty
            ...     
 936     uncertainty
 1524    negative   
 1415    negative   
 1223    negative   
 1548    uncertainty
 Name: Label, Length: 500, dtype: object)

In [ ]:
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
nb.fit(vect_train,y_train)
naive_train=nb.score(vect_train, y_train)
naive_test=nb.score(vect_test, y_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(vect_train,y_train)
knn_train=knn.score(vect_train, y_train)
knn_test=knn.score(vect_test, y_test)

In [ ]:


svm = SVC(C=1.0,kernel="rbf")
svm.fit(vect_train,y_train)
svm_train=svm.score(vect_train, y_train)
svm_test=svm.score(vect_test, y_test)

In [ ]:
# import pandas as pd/


In [ ]:
Scores={"KNN":[knn_train,knn_test],
        "SVM":[svm_train,svm_test],
        "Naive Bayes":[naive_train,naive_test]}

row=["Train Score","Test Score"]

df_score=pd.DataFrame(Scores,index=row)

In [ ]:
df_score

,KNN,SVM,Naive Bayes
Train Score,0.748,0.998667,0.988
Test Score,0.590,0.930000,0.440


In [ ]:
def lower_str(sentences):
  if type(sentences)!=str :
    sentences=sentences.astype(str)
  sentences=sentences.lower()
  return sentences

sentence="I AM so happy since i have completed my dATA SCience course from https://aiadventures.com.google . Now i will start with my machine learning course soon"
out1=lower_str(sentence)

In [ ]:
out1

'i am so happy since i have completed my data science course from https://aiadventures.com.google . now i will start with my machine learning course soon'

In [ ]:
import string
def punc(x):
  punctuations=set(string.punctuation)
  k=list(punctuations)
  emp=[]
  emp1=""
  for j in x:
    if j not  in k:
      emp1+=j
  emp.append(emp1)
  return emp

out2=punc(out1)

In [ ]:
out2

['i am so happy since i have completed my data science course from httpsaiadventurescomgoogle  now i will start with my machine learning course soon']

In [ ]:
# import nltk
# from nltk.corpus import stopwords
# stopwords.words("english")

In [ ]:
# import nltk
# nltk.download()
# # DWONLOAD-->stopwords-->QUIT
# import nltk
# from nltk.corpus import stopwords
# import nltk
# from nltk.corpus import stopwords
# stopwords.words("english")

def stopwords_(y):
  df_li=[]
  sent_li=[]
  words_li=[]
  for i in y:
    for word in i.split():
      if word not in stopwords.words('english'):
        words_li.append(word)
    sent_li.append(" ".join(words_li))
    return sent_li

out3=stopwords_(out2)

In [ ]:
out3

['happy since completed data science course httpsaiadventurescomgoogle start machine learning course soon']

In [ ]:
import re
def links(z):
  for i in z:

    z1=re.sub(r"\b" + "https" + r"\w+", "", i)
    return z1

out4=links(out3)

In [ ]:
out4

'happy since completed data science course  start machine learning course soon'

In [ ]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')
def token(z):
  token=z.split()

  return token

out5=token(out4)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:
out5

['happy',
 'since',
 'completed',
 'data',
 'science',
 'course',
 'start',
 'machine',
 'learning',
 'course',
 'soon']

In [ ]:
def lemmatization_of_testds(k):
  s=nltk.pos_tag(k)
  return s
out6=lemmatization_of_testds(out5)

In [ ]:
out6

[('happy', 'JJ'),
 ('since', 'IN'),
 ('completed', 'VBN'),
 ('data', 'NNS'),
 ('science', 'NN'),
 ('course', 'NN'),
 ('start', 'NN'),
 ('machine', 'NN'),
 ('learning', 'VBG'),
 ('course', 'NN'),
 ('soon', 'RB')]

In [ ]:
def lem_1(i):
    if i.startswith('J'):
        return wordnet.ADJ
    elif i.startswith('V'):
        return wordnet.VERB
    elif i.startswith('N'):
        return wordnet.NOUN
    elif i.startswith('R'):
        return wordnet.ADV
    else:
        return ''


In [ ]:
lem=list(map(lambda x: {i:lem_1(j) for i,j in out6 },out6))
lem


In [ ]:
def lem_2(lem):

  lemmatizer = WordNetLemmatizer()
  list33=[]
  # print(lem)
  dictionary = {key: value for key, value in lem}
  # print(dictionary)
  list3=[]
  for k,v in dictionary.items():
    print(k,v,lem_1(v))
    if lem_1(v)=='':
      v='n'
    else:
      v=lem_1(v)
    lemmatized_words=lemmatizer.lemmatize(k, pos=v)
    list3.append(lemmatized_words)
  list33.append(" ".join(list3))
  return list33

out8=lem_2(out6)

happy JJ a
since IN 
completed VBN v
data NNS n
science NN n
course NN n
start NN n
machine NN n
learning VBG v
soon RB r


In [ ]:
out8

['happy since complete data science course start machine learn soon']

In [ ]:
vect_test = vectorizer.transform(out8).toarray()
vect_test

array([[0, 0, 0, ..., 0, 0, 0]])

In [ ]:
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
nb.fit(vect_train,y_train)
predict=nb.predict(vect_train)

In [ ]:
actual=y_train


In [ ]:
from sklearn.metrics._plot.confusion_matrix import confusion_matrix
from sklearn.metrics import confusion_matrix

cm=confusion_matrix(actual,predict)
cm

array([[313,   0,   0,   0],
       [  3, 401,   0,   7],
       [  0,   2, 447,   6],
       [  0,   0,   0, 321]])

In [ ]:
tn,fp,fn,tp=cm#.ravel()

In [ ]:
tn,fp,fn,tp

(array([313,   0,   0,   0]),
 array([  3, 401,   0,   7]),
 array([  0,   2, 447,   6]),
 array([  0,   0,   0, 321]))

In [ ]:
precision = tp / (tp + fp)
precision

<ipython-input-315-14cf9d9238e4>:1: RuntimeWarning: invalid value encountered in true_divide
  precision = tp / (tp + fp)


array([0.        , 0.        ,        nan, 0.97865854])

In [ ]:
recall = tp / (tp + fn)
recall

<ipython-input-316-b8afcec01478>:1: RuntimeWarning: invalid value encountered in true_divide
  recall = tp / (tp + fn)


array([       nan, 0.        , 0.        , 0.98165138])

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
 print(classification_report(actual, predict))

              precision    recall  f1-score   support

   litigious       0.99      1.00      1.00       313
    negative       1.00      0.98      0.99       411
    positive       1.00      0.98      0.99       455
 uncertainty       0.96      1.00      0.98       321

    accuracy                           0.99      1500
   macro avg       0.99      0.99      0.99      1500
weighted avg       0.99      0.99      0.99      1500



In [ ]:
df_score

,KNN,SVM,Naive Bayes
Train Score,0.748,0.998667,0.988
Test Score,0.590,0.930000,0.440
